# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_sent_count', models.IntegerField(blank=True, default=0, null=True)),
                ('transactional_count', models.IntegerField(blank=True, default=0, null=True)),
                ('transaction_money', models.IntegerField(blank=True, default=0, null=True)),
                ('trasaction_type', models.PositiveSmallIntegerField(choices=[(1, 'CREDIT'), (2, 'DEBIT')], default=0)),
                ('trasaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_mail_Record',
            },
        ),
    ]
